import { combineDaysAndGroups } from "./utils.js";
const groups = [
  { _id: "group-id-1", group_name: "100-200" },
  { _id: "group-id-2", group_name: "300-400" },
  { _id: "group-id-3", group_name: "500-600" },
];

test("lists are empty", () => {
  expect(combineDaysAndGroups([], [])).toStrictEqual([]);
});

test("Group/Days list is null", () => {
  const errorMessage = "Invalid data, check input and try again!";
  const regex = new RegExp("^" + errorMessage + "$");
  expect(() => combineDaysAndGroups([], null)).toThrow(errorMessage);
  expect(() => combineDaysAndGroups(null, [])).toThrow(regex);
  expect(() => combineDaysAndGroups(null, null)).toThrow(errorMessage);
});

test("Group 100-200 has days, other groups have no days", () => {
  const daysForOneGroup = [
    {
      id: "day-id-1",
      group_id: "group-id-1",
      date: "2023-11-27",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-2",
      group_id: "group-id-1",
      date: "2023-11-28",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-3",
      group_id: "group-id-1",
      date: "2023-11-29",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-4",
      group_id: "group-id-1",
      date: "2023-11-30",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-5",
      group_id: "group-id-1",
      date: "2023-11-31",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "13:30",
      day_sponsors: [],
    },
    {
      id: "day-id-6",
      group_id: "group-id-1",
      date: "2023-11-31",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "13:30",
      end_time: "17:30",
      day_sponsors: [],
    },
    {
      id: "day-id-7",
      group_id: "group-id-1",
      date: "2023-11-31",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "17:30",
      end_time: "20:30",
      day_sponsors: [],
    },
  ];
  const oneGroupHasDays = [
    {
      id: "group-id-1",
      group_name: "100-200",
      week_schedule: [
        {
          id: 1,
          date: "2023-11-27",
          dayEvents: [
            {
              id: "day-id-1",
              group_id: "group-id-1",
              date: "2023-11-27",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 2,
          date: "2023-11-28",
          dayEvents: [
            {
              id: "day-id-2",
              group_id: "group-id-1",
              date: "2023-11-28",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 3,
          date: "2023-11-29",
          dayEvents: [
            {
              id: "day-id-3",
              group_id: "group-id-1",
              date: "2023-11-29",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 4,
          date: "2023-11-30",
          dayEvents: [
            {
              id: "day-id-4",
              group_id: "group-id-1",
              date: "2023-11-30",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 5,
          date: "2023-11-31",
          dayEvents: [
            {
              id: "day-id-5",
              group_id: "group-id-1",
              date: "2023-11-31",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "13:30",
              day_sponsors: [],
            },
            {
              id: "day-id-6",
              group_id: "group-id-1",
              date: "2023-11-31",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "13:30",
              end_time: "17:30",
              day_sponsors: [],
            },
            {
              id: "day-id-7",
              group_id: "group-id-1",
              date: "2023-11-31",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "17:30",
              end_time: "20:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
      ],
    },
    {
      id: "group-id-2",
      group_name: "300-400",
      week_schedule: [],
    },
    {
      id: "group-id-3",
      group_name: "500-600",
      week_schedule: [],
    },
  ];
  expect(combineDaysAndGroups(daysForOneGroup, groups)).toStrictEqual(
    oneGroupHasDays
  );
});

test("All groups have days schedule", () => {
  const allFOrAllGroups = [
    {
      id: "day-id-1",
      group_id: "group-id-1",
      date: "2023-11-27",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-2",
      group_id: "group-id-1",
      date: "2023-11-28",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-3",
      group_id: "group-id-1",
      date: "2023-11-29",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-4",
      group_id: "group-id-1",
      date: "2023-11-30",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-5",
      group_id: "group-id-1",
      date: "2023-11-31",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "13:30",
      day_sponsors: [],
    },
    {
      id: "day-id-6",
      group_id: "group-id-1",
      date: "2023-11-31",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "13:30",
      end_time: "17:30",
      day_sponsors: [],
    },
    {
      id: "day-id-7",
      group_id: "group-id-1",
      date: "2023-11-31",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "17:30",
      end_time: "20:30",
      day_sponsors: [],
    },

    {
      id: "day-id-8",
      group_id: "group-id-2",
      date: "2023-11-27",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-9",
      group_id: "group-id-2",
      date: "2023-11-28",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-10",
      group_id: "group-id-2",
      date: "2023-11-29",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-11",
      group_id: "group-id-2",
      date: "2023-11-30",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-12",
      group_id: "group-id-2",
      date: "2023-11-31",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "13:30",
      day_sponsors: [],
    },
    {
      id: "day-id-13",
      group_id: "group-id-2",
      date: "2023-11-31",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "13:30",
      end_time: "17:30",
      day_sponsors: [],
    },
    {
      id: "day-id-14",
      group_id: "group-id-2",
      date: "2023-11-31",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "17:30",
      end_time: "20:30",
      day_sponsors: [],
    },
    {
      id: "day-id-15",
      group_id: "group-id-3",
      date: "2023-11-27",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-16",
      group_id: "group-id-3",
      date: "2023-11-28",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-17",
      group_id: "group-id-3",
      date: "2023-11-29",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-18",
      group_id: "group-id-3",
      date: "2023-11-30",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-19",
      group_id: "group-id-3",
      date: "2023-11-31",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "13:30",
      day_sponsors: [],
    },
    {
      id: "day-id-20",
      group_id: "group-id-3",
      date: "2023-11-31",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "13:30",
      end_time: "17:30",
      day_sponsors: [],
    },
    {
      id: "day-id-21",
      group_id: "group-id-3",
      date: "2023-11-31",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "17:30",
      end_time: "20:30",
      day_sponsors: [],
    },
    {
      id: "day-id-21",
      group_id: "group-id-3",
      date: "2023-11-28",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "20:30",
      end_time: "22:30",
      day_sponsors: [],
    },
  ];
  const allGroupsHaveDays = [
    {
      id: "group-id-1",
      group_name: "100-200",
      week_schedule: [
        {
          id: 1,
          date: "2023-11-27",
          dayEvents: [
            {
              id: "day-id-1",
              group_id: "group-id-1",
              date: "2023-11-27",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 2,
          date: "2023-11-28",
          dayEvents: [
            {
              id: "day-id-2",
              group_id: "group-id-1",
              date: "2023-11-28",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 3,
          date: "2023-11-29",
          dayEvents: [
            {
              id: "day-id-3",
              group_id: "group-id-1",
              date: "2023-11-29",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 4,
          date: "2023-11-30",
          dayEvents: [
            {
              id: "day-id-4",
              group_id: "group-id-1",
              date: "2023-11-30",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 5,
          date: "2023-11-31",
          dayEvents: [
            {
              id: "day-id-5",
              group_id: "group-id-1",
              date: "2023-11-31",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "13:30",
              day_sponsors: [],
            },
            {
              id: "day-id-6",
              group_id: "group-id-1",
              date: "2023-11-31",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "13:30",
              end_time: "17:30",
              day_sponsors: [],
            },
            {
              id: "day-id-7",
              group_id: "group-id-1",
              date: "2023-11-31",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "17:30",
              end_time: "20:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
      ],
    },
    {
      id: "group-id-2",
      group_name: "300-400",
      week_schedule: [
        {
          id: 6,
          date: "2023-11-27",
          dayEvents: [
            {
              id: "day-id-8",
              group_id: "group-id-2",
              date: "2023-11-27",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 7,
          date: "2023-11-28",
          dayEvents: [
            {
              id: "day-id-9",
              group_id: "group-id-2",
              date: "2023-11-28",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 8,
          date: "2023-11-29",
          dayEvents: [
            {
              id: "day-id-10",
              group_id: "group-id-2",
              date: "2023-11-29",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 9,
          date: "2023-11-30",
          dayEvents: [
            {
              id: "day-id-11",
              group_id: "group-id-2",
              date: "2023-11-30",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 10,
          date: "2023-11-31",
          dayEvents: [
            {
              id: "day-id-12",
              group_id: "group-id-2",
              date: "2023-11-31",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "13:30",
              day_sponsors: [],
            },
            {
              id: "day-id-13",
              group_id: "group-id-2",
              date: "2023-11-31",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "13:30",
              end_time: "17:30",
              day_sponsors: [],
            },
            {
              id: "day-id-14",
              group_id: "group-id-2",
              date: "2023-11-31",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "17:30",
              end_time: "20:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
      ],
    },
    {
      id: "group-id-3",
      group_name: "500-600",
      week_schedule: [
        {
          id: 11,
          date: "2023-11-27",
          dayEvents: [
            {
              id: "day-id-15",
              group_id: "group-id-3",
              date: "2023-11-27",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 12,
          date: "2023-11-28",
          dayEvents: [
            {
              id: "day-id-16",
              group_id: "group-id-3",
              date: "2023-11-28",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
            {
              id: "day-id-21",
              group_id: "group-id-3",
              date: "2023-11-28",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "20:30",
              end_time: "22:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 13,
          date: "2023-11-29",
          dayEvents: [
            {
              id: "day-id-17",
              group_id: "group-id-3",
              date: "2023-11-29",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 14,
          date: "2023-11-30",
          dayEvents: [
            {
              id: "day-id-18",
              group_id: "group-id-3",
              date: "2023-11-30",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 15,
          date: "2023-11-31",
          dayEvents: [
            {
              id: "day-id-19",
              group_id: "group-id-3",
              date: "2023-11-31",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "13:30",
              day_sponsors: [],
            },
            {
              id: "day-id-20",
              group_id: "group-id-3",
              date: "2023-11-31",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "13:30",
              end_time: "17:30",
              day_sponsors: [],
            },
            {
              id: "day-id-21",
              group_id: "group-id-3",
              date: "2023-11-31",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "17:30",
              end_time: "20:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
      ],
    },
  ];
  expect(combineDaysAndGroups(allFOrAllGroups, groups)).toStrictEqual(
    allGroupsHaveDays
  );
});

test("Some days have reference to non existing group", () => {
  const dayHasUnknownGroup = [
    {
      id: "day-id-1",
      group_id: "group-id-5",
      date: "2023-11-27",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-2",
      group_id: "group-id-5",
      date: "2023-11-28",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-3",
      group_id: "group-id-5",
      date: "2023-11-29",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-4",
      group_id: "group-id-5",
      date: "2023-11-30",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-5",
      group_id: "group-id-5",
      date: "2023-11-31",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "13:30",
      day_sponsors: [],
    },
    {
      id: "day-id-6",
      group_id: "group-id-5",
      date: "2023-11-31",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "13:30",
      end_time: "17:30",
      day_sponsors: [],
    },
    {
      id: "day-id-7",
      group_id: "group-id-5",
      date: "2023-11-31",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "17:30",
      end_time: "20:30",
      day_sponsors: [],
    },
    {
      id: "day-id-8",
      group_id: "group-id-1",
      date: "2023-11-27",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-9",
      group_id: "group-id-1",
      date: "2023-11-28",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-10",
      group_id: "group-id-1",
      date: "2023-11-29",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-11",
      group_id: "group-id-1",
      date: "2023-11-30",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "19:30",
      day_sponsors: [],
    },
    {
      id: "day-id-12",
      group_id: "group-id-1",
      date: "2023-11-31",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "10:30",
      end_time: "13:30",
      day_sponsors: [],
    },
    {
      id: "day-id-13",
      group_id: "group-id-1",
      date: "2023-11-31",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "13:30",
      end_time: "17:30",
      day_sponsors: [],
    },
    {
      id: "day-id-14",
      group_id: "group-id-2",
      date: "2023-11-31",
      programma: "test",
      extra_info: "test",
      start_location: "test",
      end_location: "test",
      start_time: "17:30",
      end_time: "20:30",
      day_sponsors: [],
    },
  ];
  const groupsHaveNoDays = [
    {
      id: "group-id-1",
      group_name: "100-200",
      week_schedule: [
        {
          id: 1,
          date: "2023-11-27",
          dayEvents: [
            {
              id: "day-id-8",
              group_id: "group-id-1",
              date: "2023-11-27",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 2,
          date: "2023-11-28",
          dayEvents: [
            {
              id: "day-id-9",
              group_id: "group-id-1",
              date: "2023-11-28",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 3,
          date: "2023-11-29",
          dayEvents: [
            {
              id: "day-id-10",
              group_id: "group-id-1",
              date: "2023-11-29",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 4,
          date: "2023-11-30",
          dayEvents: [
            {
              id: "day-id-11",
              group_id: "group-id-1",
              date: "2023-11-30",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "19:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
        {
          id: 5,
          date: "2023-11-31",
          dayEvents: [
            {
              id: "day-id-12",
              group_id: "group-id-1",
              date: "2023-11-31",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "10:30",
              end_time: "13:30",
              day_sponsors: [],
            },
            {
              id: "day-id-13",
              group_id: "group-id-1",
              date: "2023-11-31",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "13:30",
              end_time: "17:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
      ],
    },
    {
      id: "group-id-2",
      group_name: "300-400",
      week_schedule: [
        {
          id: 6,
          date: "2023-11-31",
          dayEvents: [
            {
              id: "day-id-14",
              group_id: "group-id-2",
              date: "2023-11-31",
              programma: "test",
              extra_info: "test",
              start_location: "test",
              end_location: "test",
              start_time: "17:30",
              end_time: "20:30",
              day_sponsors: [],
            },
          ],
          day_sponsors: [],
        },
      ],
    },
    {
      id: "group-id-3",
      group_name: "500-600",
      week_schedule: [],
    },
  ];
  expect(combineDaysAndGroups(dayHasUnknownGroup, groups)).toStrictEqual(
    groupsHaveNoDays
  );
});
